### ISSUE TITLE
Sig validation needs to anchor to IP address

### ISSUE THREAD

**Issue by tojens-ietf** [boucadair/add-resolver-information#7]
In the description for sig validation:

> DNS clients using DDR for encrypted resolver discovery quering for an RESINFO RR MUST validate the signature in the "sig" attribute for data origin authentication.  If the signature validation fails, the DNS client MUST reject the RESINFO RR.

Nit: s/quering/querying

The point of DDR is that the trust anchor is the original IP address of the resolver. I think it's worth calling out there that the MUST validate involves ensuring the certificate that signed can also claim the IP address that DDR used to validate.

That clarification may be more appropriate in this text which already describes the requirements for validation:

> The signature algorithm MUST be compatible with the public key in the DNS server's end-entity certificate.  As a	 reminder, the server's end-entity certificate's public key will be compatible with the selected authentication algorithm from the client's "signature_algorithms" TLS extension.

**Comment by boucadair** [comment]
> In the description for sig validation:
> 
> > DNS clients using DDR for encrypted resolver discovery quering for an RESINFO RR MUST validate the signature in the "sig" attribute for data origin authentication.  If the signature validation fails, the DNS client MUST reject the RESINFO RR.
> 
> Nit: s/quering/querying
> 

I think you were looking at an old version as we already fixed that one when preparing -04. The public version does not include that nit.

> The point of DDR is that the trust anchor is the original IP address of the resolver. I think it's worth calling out there that the MUST validate involves ensuring the certificate that signed can also claim the IP address that DDR used to validate.
> 
> That clarification may be more appropriate in this text which already describes the requirements for validation:
> 
> > The signature algorithm MUST be compatible with the public key in the DNS server's end-entity certificate.  As a	 reminder, the server's end-entity certificate's public key will be compatible with the selected authentication algorithm from the client's "signature_algorithms" TLS extension.

We need to avoid introducing redundant requirements compared to what is already covered in DDR. Please check https://github.com/boucadair/add-resolver-information/pull/8/files and let us know if that is OK with you.

**Comment by tojens-ietf** [comment]
It's the right direction, but this does not make IP in the signing cert verification normative the way it is grammatically structured. I get not wanting to duplicate DDR text, but this is also slightly different than DDR (at sig verification time, not during TLS handshake), and that distinction ought to be clear so no implementor thinks this just means they had to follow DDR before accepting the connection (that isn't enough).

This is the only thing blocking me from calling the new version ready to approve and get WG consensus.

**Comment by boucadair** [comment]
Thanks @mstojens for checking. 

I made another attempt that you can find at: https://github.com/boucadair/add-resolver-information/pull/9/files

Hope this is better.

**Comment by tojens-ietf** [comment]
Love it, thank you @boucadair ! Looking forward to the rev.
